version: '2'
services:
  web:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - ui
      - image
      - response
  ui:
    image: asifrc/rorschach-ui
  image:
    image: asifrc/rorschach-image
  response:
    image: asifrc/rorschach-response
